<?php
return [
    'hu' => [
        'section_personal'    => 'Személyes adatok',
        'section_declaration' => 'Nyilatkozat',
        'section_signature'   => 'Aláírás',
        'section_gdpr'        => 'Adatkezelés',
        'btn_submit'          => 'Beküldés',
        'btn_clear'           => 'Törlés',
        'btn_new'             => 'Új nyilatkozat',
        'date_label'          => 'Kelt.',
        'sig_hint'            => 'Kérjük, írja alá ujjával vagy egérrel.',
        'gdpr_show'           => '⊕ Adatkezelési tájékoztató megtekintése',
        'gdpr_hide'           => '⊖ Bezárás',
        'success'             => 'Nyilatkozata sikeresen beküldve! Köszönjük!',
        'err_missing'         => 'Kérjük töltse ki az összes kötelező mezőt!',
        'err_signature'       => 'Kérjük írja alá a nyilatkozatot!',
        'err_gdpr'            => 'Az adatkezelési hozzájárulás megadása kötelező!',
        'err_db'              => 'Adatbázis hiba, kérjük próbálja újra!',
        'err_rate_limit'      => 'Túl sok próbálkozás! Kérjük próbálja újra néhány perc múlva.',
        'placeholder_name'    => 'Teljes név',
        'placeholder_company' => 'Cég neve',
        'placeholder_contact' => 'Kapcsolattartó neve',
        'lang_label'          => 'Nyelv',
        'auto_reset'          => 'Új nyilatkozat automatikusan indul {s} másodperc múlva…',
    ],
    'en' => [
        'section_personal'    => 'Personal Information',
        'section_declaration' => 'Declaration',
        'section_signature'   => 'Signature',
        'section_gdpr'        => 'Data Privacy',
        'btn_submit'          => 'Submit',
        'btn_clear'           => 'Clear',
        'btn_new'             => 'New declaration',
        'date_label'          => 'Date',
        'sig_hint'            => 'Please sign with your finger or mouse.',
        'gdpr_show'           => '⊕ View Privacy Notice',
        'gdpr_hide'           => '⊖ Close',
        'success'             => 'Your declaration has been submitted successfully! Thank you!',
        'err_missing'         => 'Please fill in all required fields!',
        'err_signature'       => 'Please sign the declaration!',
        'err_gdpr'            => 'GDPR consent is required!',
        'err_db'              => 'Database error, please try again!',
        'err_rate_limit'      => 'Too many attempts! Please try again in a few minutes.',
        'placeholder_name'    => 'Full name',
        'placeholder_company' => 'Company name',
        'placeholder_contact' => 'Contact person\'s name',
        'lang_label'          => 'Language',
        'auto_reset'          => 'A new form will start automatically in {s} seconds…',
    ],
];
